"use client";

export interface Player {
  player_id: string;
  player_name: string;
  team_name: string;
  player_image: string;
  player_age: number;
  player_type: string;
}

export const recommendedPlayers: Player[] = [
  {
    player_id: "1",
    player_name: "Lionel Messi",
    team_name: "Paris Saint-Germain",
    player_image: "https://via.placeholder.com/150",
    player_age: 34,
    player_type: "Forwards",
  },
  {
    player_id: "2",
    player_name: "Cristiano Ronaldo",
    team_name: "Al Nassr",
    player_image: "https://via.placeholder.com/150",
    player_age: 36,
    player_type: "Forwards",
  },
  {
    player_id: "3",
    player_name: "Neymar Jr.",
    team_name: "Paris Saint-Germain",
    player_image: "https://via.placeholder.com/150",
    player_age: 29,
    player_type: "Forwards",
  },
  {
    player_id: "4",
    player_name: "Kylian Mbappe",
    team_name: "Paris Saint-Germain",
    player_image: "https://via.placeholder.com/150",
    player_age: 22,
    player_type: "Forwards",
  },
  {
    player_id: "5",
    player_name: "Robert Lewandowski",
    team_name: "FC Barcelona",
    player_image: "https://via.placeholder.com/150",
    player_age: 33,
    player_type: "Forwards",
  },
  {
    player_id: "6",
    player_name: "Erling Haaland",
    team_name: "Manchester City",
    player_image: "https://via.placeholder.com/150",
    player_age: 21,
    player_type: "Forwards",
  },
  {
    player_id: "7",
    player_name: "Luka Modric",
    team_name: "Real Madrid",
    player_image: "https://via.placeholder.com/150",
    player_age: 35,
    player_type: "Midfielders",
  },
  {
    player_id: "8",
    player_name: "Kevin De Bruyne",
    team_name: "Manchester City",
    player_image: "https://via.placeholder.com/150",
    player_age: 30,
    player_type: "Midfielders",
  },
  {
    player_id: "9",
    player_name: "Mohamed Salah",
    team_name: "Liverpool",
    player_image: "https://via.placeholder.com/150",
    player_age: 29,
    player_type: "Forwards",
  },
  {
    player_id: "10",
    player_name: "Harry Kane",
    team_name: "Tottenham Hotspur",
    player_image: "https://via.placeholder.com/150",
    player_age: 28,
    player_type: "Forwards",
  },
  {
    player_id: "11",
    player_name: "Sergio Ramos",
    team_name: "Paris Saint-Germain",
    player_image: "https://via.placeholder.com/150",
    player_age: 35,
    player_type: "Defenders",
  },
  {
    player_id: "12",
    player_name: "Virgil van Dijk",
    team_name: "Liverpool",
    player_image: "https://via.placeholder.com/150",
    player_age: 29,
    player_type: "Defenders",
  },
  {
    player_id: "13",
    player_name: "Joshua Kimmich",
    team_name: "Bayern Munich",
    player_image: "https://via.placeholder.com/150",
    player_age: 26,
    player_type: "Midfielders",
  },
  {
    player_id: "14",
    player_name: "Bruno Fernandes",
    team_name: "Manchester United",
    player_image: "https://via.placeholder.com/150",
    player_age: 27,
    player_type: "Midfielders",
  },
  {
    player_id: "15",
    player_name: "Karim Benzema",
    team_name: "Real Madrid",
    player_image: "https://via.placeholder.com/150",
    player_age: 33,
    player_type: "Forwards",
  },
  {
    player_id: "16",
    player_name: "Jan Oblak",
    team_name: "Atletico Madrid",
    player_image: "https://via.placeholder.com/150",
    player_age: 28,
    player_type: "Goalkeepers",
  },
  {
    player_id: "17",
    player_name: "Gianluigi Donnarumma",
    team_name: "Paris Saint-Germain",
    player_image: "https://via.placeholder.com/150",
    player_age: 22,
    player_type: "Goalkeepers",
  },
  {
    player_id: "18",
    player_name: "Trent Alexander-Arnold",
    team_name: "Liverpool",
    player_image: "https://via.placeholder.com/150",
    player_age: 23,
    player_type: "Defenders",
  },
  {
    player_id: "19",
    player_name: "Alphonso Davies",
    team_name: "Bayern Munich",
    player_image: "https://via.placeholder.com/150",
    player_age: 21,
    player_type: "Defenders",
  },
  {
    player_id: "20",
    player_name: "Gerard Piqué",
    team_name: "FC Barcelona",
    player_image: "https://via.placeholder.com/150",
    player_age: 34,
    player_type: "Defenders",
  },
  {
    player_id: "21",
    player_name: "Thiago Silva",
    team_name: "Chelsea",
    player_image: "https://via.placeholder.com/150",
    player_age: 36,
    player_type: "Defenders",
  },
  {
    player_id: "22",
    player_name: "Romelu Lukaku",
    team_name: "Chelsea",
    player_image: "https://via.placeholder.com/150",
    player_age: 28,
    player_type: "Forwards",
  },
  {
    player_id: "23",
    player_name: "Jorginho",
    team_name: "Chelsea",
    player_image: "https://via.placeholder.com/150",
    player_age: 30,
    player_type: "Midfielders",
  },
  {
    player_id: "24",
    player_name: "Paulo Dybala",
    team_name: "Juventus",
    player_image: "https://via.placeholder.com/150",
    player_age: 28,
    player_type: "Forwards",
  },
  {
    player_id: "25",
    player_name: "Ederson",
    team_name: "Manchester City",
    player_image: "https://via.placeholder.com/150",
    player_age: 28,
    player_type: "Goalkeepers",
  },
  {
    player_id: "26",
    player_name: "N'Golo Kanté",
    team_name: "Chelsea",
    player_image: "https://via.placeholder.com/150",
    player_age: 30,
    player_type: "Midfielders",
  },
  {
    player_id: "27",
    player_name: "Raheem Sterling",
    team_name: "Manchester City",
    player_image: "https://via.placeholder.com/150",
    player_age: 27,
    player_type: "Forwards",
  },
  {
    player_id: "28",
    player_name: "Luis Suárez",
    team_name: "Atletico Madrid",
    player_image: "https://via.placeholder.com/150",
    player_age: 34,
    player_type: "Forwards",
  },
  {
    player_id: "29",
    player_name: "Casemiro",
    team_name: "Real Madrid",
    player_image: "https://via.placeholder.com/150",
    player_age: 29,
    player_type: "Midfielders",
  },
  {
    player_id: "30",
    player_name: "Manuel Neuer",
    team_name: "Bayern Munich",
    player_image: "https://via.placeholder.com/150",
    player_age: 35,
    player_type: "Goalkeepers",
  },
];
